version: '3'

volumes:
  postgres-data:
    driver: local

services:
  postgres-hotel-booking:
    image: postgres:15.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: hotel-booking
    ports:
      - "10001:10001"
    command: -p 10001

#  postgres-hotel-booking:
#    image: bitnami/postgresql:15.2.0
#    volumes:
#      - postgres-data-hotel-booking:/bitnami/postgresql
#    environment:
#      POSTGRESQL_USERNAME: postgres
#      POSTGRESQL_PASSWORD: 1212
#      POSTGRESQL_DATABASE: hotel-booking
#      POSTGRESQL_PORT_NUMBER: 10001
#    ports:
#      - "10001:10001"